
!obj:pylearn2.train.Train {
  dataset: !obj:pylearn2.sandbox.nlp.datasets.shuffle2.H5Shuffle {
    path: '/data/lisatmp3/chokyun/mt/vocab.30k/bitexts.selected/binarized_text.en.h5',
    node: 'none', #('/phrases', '/indices'),
    which_set: 'train',
    frame_length: &n 7,
    stop: %(stop)s,
    load_to_memory: True,
    _iter_num_batches: 1000,
    X_labels: &l 30000,
    cache_size: 1000000,
    cache_delta: 100000,
    schwenk: True,
  },
  model: !obj:pylearn2.models.mlp.MLP {
    input_space: !obj:pylearn2.space.IndexSpace {
      dim: *n,
      max_labels: *l
    },
    layers: [
      !obj:pylearn2.sandbox.nlp.models.mlp.ProjectionLayer {
        layer_name: 'projection',
        dim: 256,
        irange: 0.01
      },
      !obj:pylearn2.models.mlp.RectifiedLinear {
        layer_name: 'h0',
        dim: 512,
        irange: 0.01
      },
      !obj:pylearn2.models.mlp.RectifiedLinear {
        layer_name: 'h1',
        dim: 256,
        irange: 0.01
      },
      !obj:pylearn2.models.mlp.Sigmoid {
        layer_name: 'output',
        dim: 6, # n - 1
        irange: 0.01
      },
    ],
  },
  algorithm: !obj:pylearn2.training_algorithms.sgd.SGD {
    batch_size: 256,
    learning_rate: .000001,
    learning_rule: !obj:pylearn2.training_algorithms.learning_rule.AdaDelta {},
    monitoring_dataset: {
      'valid': !obj:pylearn2.sandbox.nlp.datasets.shuffle2.H5Shuffle {
        path: '/data/lisatmp3/chokyun/mt/vocab.30k/bitexts.selected/binarized_text.en.h5',
        node: 'none', # ('/phrases', '/indices'),
        which_set: 'valid',
        frame_length: *n,
        _iter_num_batches: 20,
        X_labels: *l,
        load_to_memory: True,
        schwenk: True,
      },
      'train': !obj:pylearn2.sandbox.nlp.datasets.shuffle2.H5Shuffle {
        path: '/data/lisatmp3/chokyun/mt/vocab.30k/bitexts.selected/binarized_text.en.h5',
        node: 'none', # ('/phrases', '/indices'),
        which_set: 'train',
        frame_length: *n,
        start: 0,
        stop:  8e5,
        _iter_num_batches: 20,
        X_labels: *l,
        load_to_memory: True,
        schwenk: True,
      },
    },
  },
 # extensions: [
 #      !obj:pylearn2.train_extensions.WordRelationship {
 #        vocab: "/data/lisatmp3/pougetj/vocab.pkl",
 #        questions: "/data/lisatmp3/pougetj/questions-words.txt",
 #        vocab_size: *l,
 #        UNK: 1,
 #        n_batches: 4, 
 #      }
 # ],
  save_path: %(save_path)s,
  save_freq: 1,
}
